version: "3.5"

services:
  demo-db:
    container_name: database
    build:
      context: .
      dockerfile: ./db/Dockerfile.db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "demo", "-U", "postgres"]
      interval: 3s
      timeout: 10s
      retries: 3
    networks:
      - dansnetwork
    ports:
      - "5432:5432"
    user: postgres
    environment:
      - POSTGRES_DB=demo
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
  stage-demo-db:
    container_name: stage-database
    build:
      context: .
      dockerfile: ./db/Dockerfile.db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "demo", "-U", "postgres"]
      interval: 3s
      timeout: 10s
      retries: 3
    networks:
      - dansnetwork
    ports:
      - "5433:5432"
    user: postgres
    environment:
      - POSTGRES_DB=demo
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
  atlas-migrate:
    image: arigaio/atlas:latest
    command: >
      migrate apply -u postgres://postgres:password@demo-db:5432/demo?sslmode=disable
    networks:
      - dansnetwork
    depends_on:
      demo-db:
        condition: service_healthy
    volumes:
      - ./db/migrations:/migrations
  stage-atlas-migrate:
    image: arigaio/atlas:latest
    command: >
      migrate apply -u postgres://postgres:password@stage-demo-db:5432/demo?sslmode=disable
    networks:
      - dansnetwork
    depends_on:
      stage-demo-db:
        condition: service_healthy
    volumes:
      - ./db/stage-migrations:/migrations
networks:
  dansnetwork:
    name: dansnetwork
    driver: bridge
